[project]
name = "apx-aws-lambda"
type = "library"
language = "python"
ci = "github"

[source_host]
kind = "github"
repo = "actionplatform/apx-aws-lambda"

[release]
strategy = "semver"
changelog = "conventional"
